language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - EVENTSTORE_VERSION='v3.0.0'
matrix:
    allow_failures:
        - php: hhvm

before_install:
    - wget http://download.geteventstore.com/binaries/EventStore-OSS-Linux-${EVENTSTORE_VERSION}.tar.gz
    - tar xf EventStore*.tar.gz
    - cd EventStore* && ./clusternode --mem-db 2>&1> eventstore.log &
install:
    - composer install --dev --prefer-source --no-interaction

script: bin/phpunit --coverage-clover=coverage.clover --coverage-text --testdox

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - killall -SIGINT clusternode
  - cat EventStore*/eventstore.log
