language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - wget http://download.geteventstore.com/binaries/EventStore-OSS-Linux-v3.0.0.tar.gz
    - tar vxf EventStore-OSS-Linux-v3.0.0.tar.gz
    - cd EventStore* && ./clusternode --mem-db &

install:
    - composer install --dev --prefer-source --no-interaction

script: bin/phpunit --coverage-clover=coverage.clover --coverage-text --testdox

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
